#!/bin/bash

echo Updating submodules
git submodule update --init --recursive

echo Building SDL2...
cd Sources/Libs/SDL
mkdir build
cd build
../configure
make

cd ../../../

echo Building ShaderConductor...
cd Sources/Libs/ShaderConductor/
./BuildAll.py ninja clang x64 Debug
./BuildAll.py ninja clang x64 Release