#!/bin/bash

mkdir Binaries/Debug
mkdir Binaries/Release
mkdir Binaries/DebugMonolithic
mkdir Binaries/ReleaseMonolithic

cp Sources/Libs/ShaderConductor/Build/ninja-linux-clang-x64-Debug/Lib/libdxcompiler.so Binaries/Debug/libdxcompiler.so
cp Sources/Libs/ShaderConductor/Build/ninja-linux-clang-x64-Debug/Lib/libShaderConductor.so Binaries/Debug/libShaderConductor.so

cp Sources/Libs/ShaderConductor/Build/ninja-linux-clang-x64-Debug/Lib/libdxcompiler.so Binaries/DebugMonolithic/libdxcompiler.so
cp Sources/Libs/ShaderConductor/Build/ninja-linux-clang-x64-Debug/Lib/libShaderConductor.so Binaries/DebugMonolithic/libShaderConductor.so

cp Sources/Libs/ShaderConductor/Build/ninja-linux-clang-x64-Release/Lib/libdxcompiler.so Binaries/Release/libdxcompiler.so
cp Sources/Libs/ShaderConductor/Build/ninja-linux-clang-x64-Release/Lib/libShaderConductor.so Binaries/Release/libShaderConductor.so

cp Sources/Libs/ShaderConductor/Build/ninja-linux-clang-x64-Release/Lib/libdxcompiler.so Binaries/ReleaseMonolithic/libdxcompiler.so
cp Sources/Libs/ShaderConductor/Build/ninja-linux-clang-x64-Release/Lib/libShaderConductor.so Binaries/ReleaseMonolithic/libShaderConductor.so

cp Sources/Libs/SDL/build/build/.libs/libSDL2.so Binaries/Debug/libSDL2.so
cp Sources/Libs/SDL/build/build/.libs/libSDL2.so Binaries/DebugMonolithic/libSDL2.so
cp Sources/Libs/SDL/build/build/.libs/libSDL2.so Binaries/Release/libSDL2.so
cp Sources/Libs/SDL/build/build/.libs/libSDL2.so Binaries/ReleaseMonolithic/libSDL2.so