/** Reflection data generated by ZinoReflectionTool, don't modify! */

#include "Core/EngineCore.h"
#include "test.h"

RTTR_REGISTRATION
{
	/** CLASSES */ 
	rttr::registration::class_<CActorComponent>("CActorComponent")
		.property("Owner", &CActorComponent::Owner)
		.property("Owner", &CActorComponent::Owner)
		.property("Owner", &CActorComponent::Owner);
}
