FetchContent_Declare(SDL2
    URL ${CMAKE_CURRENT_SOURCE_DIR}/SDL2)
FetchContent_MakeAvailable(SDL2)
set(SDL_STATIC_BUILD CACHED BOOL OFF)
set(SDL_SHARED_BUILD CACHED BOOL ON)
set_target_properties(SDL2 PROPERTIES
    ARCHIVE_OUTPUT_DIRECTORY "${ZE_BINS_DIR}"
    LIBRARY_OUTPUT_DIRECTORY "${ZE_BINS_DIR}"
    RUNTIME_OUTPUT_DIRECTORY "${ZE_BINS_DIR}")