# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Build for windows X64
  build-windows-x64:
    # The type of runner that the job will run on
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
          submodules: recursive
    
    # Setup msbuild
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1
    
    # Download and extract precompiled shader conductor lib
    - name: download-extract-shaderconductor
      run: | 
        curl https://dl.dropboxusercontent.com/s/vn0js0up6hujz8m/Build.zip?dl=1 --output Build.zip
        powershell Expand-Archive -Force Build.zip ${{ github.workspace }}/Sources/Libs/ShaderConductor/
        shell: cmd
    
    # Generate and build sln
    - name: build-sln
      run: |
        @echo | call GenerateVS2019.bat
        msbuild Build/ProjectFiles/ZinoEngine.sln /t:build /p:Configuration="Debug" /p:Platform="x64" /p:BuildInParallel=true
        shell: cmd
